version: "3.8"
services:
  apiary:
    container_name: vue-apiary
    image: apiary
    tty: true
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: ./
      # target: developments
    volumes:
      - ./src:/apiary/src
    ports:
      - 8080:8080
      - 3000:3000
      - 5000:5000
# # for local development
# version: '3.7'
# services:
#   quasar:
#     build:
#       context: .
#       # target: 'develop-stage'
#     ports:
#     - '8080:8080'
#     volumes:
#     - '.:/apiary'
#     command: /bin/sh -c "yarn && quasar dev"